"""
Runs every query in queries.sql against data/maternal_health.db and writes
the results to sql/sql_results.md - so the SQL analysis is reproducible and
its output is reviewable without needing a SQL client installed.

Run:
    python sql/run_queries.py
"""
import os
import re
import sqlite3
import pandas as pd

HERE = os.path.dirname(os.path.abspath(__file__))
DB_PATH = os.path.join(HERE, "..", "data", "maternal_health.db")
SQL_PATH = os.path.join(HERE, "queries.sql")
OUT_PATH = os.path.join(HERE, "sql_results.md")


def split_queries(sql_text):
    """Each query section looks like:
        -- ----...
        -- Q1a. Title
        -- Purpose: ...
        -- ----...
        SELECT ...;
    Split on the dashed rule lines, then walk the resulting pieces: a piece
    holding a '-- Q<id>. <title>' comment sets the pending title; the next
    piece that contains real SQL is paired with it.
    """
    blocks = [b.strip("\n") for b in re.split(r"-- -{10,}\n", sql_text)]
    parsed = []
    pending_title = None
    for block in blocks:
        if not block.strip():
            continue
        m = re.search(r"^--\s*(Q\S*\.\s*.+)$", block, re.MULTILINE)
        sql_lines = [l for l in block.split("\n") if l.strip() and not l.strip().startswith("--")]
        query = "\n".join(sql_lines).strip()
        if m and not query:
            pending_title = m.group(1).strip()
        elif query and pending_title:
            parsed.append((pending_title, query))
            pending_title = None
    return parsed


def main():
    with open(SQL_PATH) as f:
        sql_text = f.read()
    queries = split_queries(sql_text)
    print(f"Found {len(queries)} queries.\n")

    conn = sqlite3.connect(DB_PATH)
    out_lines = ["# SQL Analysis Results\n",
                 "Generated by `sql/run_queries.py` against `data/maternal_health.db` "
                 "(1,012 cleaned rows). See `sql/queries.sql` for the full commented queries.\n"]

    for title, query in queries:
        print(f"=== {title} ===")
        try:
            df = pd.read_sql_query(query, conn)
        except Exception as e:
            print(f"  ERROR: {e}\n")
            continue
        print(df.to_string(index=False))
        print()
        out_lines.append(f"\n## {title}\n")
        out_lines.append(df.to_markdown(index=False))
        out_lines.append("\n")

    conn.close()

    with open(OUT_PATH, "w") as f:
        f.write("\n".join(out_lines))
    print(f"Results written to {OUT_PATH}")


if __name__ == "__main__":
    main()
